providers:
  google_secretmanager_1:
    kind: google_secretmanager
    maps:
      - id: gsm
        path: projects/{{ get_env(name="GCP_PROJECT_ID", default="default") }}
        keys:
          CACHIX_AUTH_TOKEN: ==
          CODECOV_TOKEN: ==
          FAST_FORWARD_PAT: ==
          GITGUARDIAN_API_KEY: ==
          UV_PUBLISH_TOKEN: ==
