name: Python Release

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Name of the package"
        required: true
        type: string
      artifact-name:
        description: "Name of the artifact to download"
        required: true
        type: string
      version:
        description: "Version to release"
        required: true
        type: string

  workflow_call:
    inputs:
      package-name:
        description: "Name of the package"
        required: true
        type: string
      artifact-name:
        description: "Name of the artifact to download"
        required: true
        type: string
      version:
        description: "Version to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: release
      url: https://pypi.org/project/${{ inputs.package-name }}/${{ inputs.version }}/
    steps:
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # ratchet:actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # ratchet:pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist
